name: Node.js CI with MariaDB

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mariadb:
        image: mariadb:10.5.12
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: live
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: ğŸ› Checkout repository code
        uses: actions/checkout@v2

      - name: ğŸ“ Verify MariaDB connection / Create database / Set port
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done
          echo "CREATE DATABASE IF NOT EXISTS test;" > test.sql
          mysql -uroot -ppassword -h"127.0.0.1" -P"3306" < test.sql

      - name: ğŸ— Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com

      - name: ğŸ“¦ Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TO_REPO_OF_ORT_PRIVATE }}

      - name: ğŸ§ª Jest
        run: echo "NODE_ENV=live" >> $GITHUB_ENV
      - run: npm run db:setup
      - run: npm run db:seed:master
      - run: npm run test:live --empty tests/empty/__tests__/
      - run: npm run test:live --empty tests/empty/_live/
      - run: npm run test:live --empty tests/empty/_orders/
      - run: npm run db:seed:dev
      - run: npm run test:live --seeded tests/__tests__/
      - run: npm run test:live --seeded tests/_live/
      - run: npm run test:live --seeded tests/_orders/
